import * as THREE from 'three';
import { scrollState } from './scroll-state.js';
const canvas=document.querySelector('#hvac'),wrap=canvas.parentElement;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setClearColor(0x061c2b,0);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(6,4.6,7);camera.lookAt(0,1.6,0);
scene.add(new THREE.HemisphereLight(0xe5f5ff,0x102a42,2.2));const sun=new THREE.DirectionalLight(0xfff7e8,4);sun.position.set(0,7,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-6;sun.shadow.camera.right=6;sun.shadow.camera.top=7;sun.shadow.camera.bottom=-5;sun.shadow.bias=-.001;scene.add(sun);const rim=new THREE.DirectionalLight(0x81ceff,5);rim.position.set(-3,3,-5);scene.add(rim);const redLight=new THREE.DirectionalLight(0xff7777,.7);redLight.position.set(5,0,-2);scene.add(redLight);
const silver=new THREE.MeshStandardMaterial({color:0xa9b3b7,metalness:.6,roughness:.36}),dark=new THREE.MeshStandardMaterial({color:0x183441,metalness:.3,roughness:.6}),white=new THREE.MeshStandardMaterial({color:0xd5dcdb,metalness:.4,roughness:.42});
function box(w,h,d,mat,x,y,z,parent=scene){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
const unit=new THREE.Group();scene.add(unit);unit.position.set(2.8,.35,0);unit.rotation.y=-.15;box(2.8,.16,2.6,new THREE.MeshStandardMaterial({color:0x002d4b}),0,.15,0,unit);box(2.25,2.05,2.05,dark,0,1.28,0,unit);box(2.4,.15,2.2,white,0,2.36,0,unit);box(2.4,.12,2.2,silver,0,.3,0,unit);
for(let i=0;i<29;i++){const x=-1.08+i*2.16/28;box(.026,1.8,.06,silver,x,1.29,1.06,unit);box(.026,1.8,.06,silver,x,1.29,-1.06,unit);box(.06,1.8,.026,silver,1.16,1.29,x*.91,unit);box(.06,1.8,.026,silver,-1.16,1.29,x*.91,unit);}for(const x of [-1.13,1.13])for(const z of [-1.04,1.04])box(.1,2.05,.1,white,x,1.3,z,unit);
const ringMat=new THREE.MeshStandardMaterial({color:0x162b34,metalness:.5,roughness:.5});const fan=new THREE.Group();fan.position.y=2.46;unit.add(fan);for(let i=0;i<5;i++){const blade=box(.24,.035,.75,ringMat,0,0,.35,fan);blade.rotation.y=i*Math.PI*2/5;blade.position.set(Math.sin(blade.rotation.y)*.35,0,Math.cos(blade.rotation.y)*.35);}for(let r=.2;r<.96;r+=.1){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.014,6,64),ringMat);ring.rotation.x=Math.PI/2;ring.position.y=2.51;unit.add(ring);}for(let i=0;i<8;i++){const spoke=box(.023,.03,1.9,ringMat,0,2.52,0,unit);spoke.rotation.y=i*Math.PI/8;}
box(.65,.25,.035,new THREE.MeshStandardMaterial({color:0xb0272e}),.52,1.98,1.11,unit);
const ground=new THREE.Mesh(new THREE.CircleGeometry(12,64),new THREE.ShadowMaterial({opacity:.15}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const texCanvas=document.createElement('canvas');texCanvas.width=988;texCanvas.height=520;const ctx=texCanvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,988,520);ctx.fillStyle='#b0272e';for(let i=0;i<13;i+=2)ctx.fillRect(0,i*40,988,40);ctx.fillStyle='#002d4b';ctx.fillRect(0,0,395,280);ctx.fillStyle='#fff';for(let row=0;row<9;row++){const count=row%2===0?6:5;for(let col=0;col<count;col++){const x=(col+1)*395/7+(count===5?395/14:0),y=(row+1)*28;ctx.beginPath();for(let p=0;p<10;p++){const a=-Math.PI/2+p*Math.PI/5,r=p%2?4.3:10;ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r);}ctx.closePath();ctx.fill();}}
const texture=new THREE.CanvasTexture(texCanvas);texture.colorSpace=THREE.SRGBColorSpace;const flagGeo=new THREE.PlaneGeometry(3.8,2,40,20);flagGeo.translate(1.9,0,0);const flag=new THREE.Mesh(flagGeo,new THREE.MeshStandardMaterial({map:texture,side:THREE.DoubleSide,roughness:.9}));flag.position.set(-2.25,3.65,-1.5);flag.rotation.y=.13;scene.add(flag);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,4.85,16),silver);pole.position.set(-2.25,2.425,-1.5);scene.add(pole);const cap=new THREE.Mesh(new THREE.SphereGeometry(.09,16,16),silver);cap.position.set(-2.25,4.89,-1.5);scene.add(cap);
const flagGroup=new THREE.Group();scene.add(flagGroup);flagGroup.add(flag,pole,cap);flagGroup.position.set(2.8,.3,-2.5);flag.scale.set(1.6,1.4,1);flag.position.y=4.3;pole.scale.y=1.2;cap.position.y=5.9;
const air=new THREE.Group();scene.add(air);const airMat=new THREE.LineBasicMaterial({color:0x76bce0,transparent:true,opacity:.2});
for(let n=0;n<12;n++){const points=[];for(let i=0;i<=90;i++){const t=i/90;points.push(new THREE.Vector3(-9+t*20,-.8+n*.24+Math.sin(t*6+n*.13)*.5,-3+Math.sin(t*5+n*.3)*2));}air.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),airMat));}
const speckGeo=new THREE.BufferGeometry(),specks=[];for(let i=0;i<140;i++)specks.push(Math.sin(i*127.1)*15,Math.cos(i*63.7)*7,Math.sin(i*17.3)*8-6);speckGeo.setAttribute('position',new THREE.Float32BufferAttribute(specks,3));const particles=new THREE.Points(speckGeo,new THREE.PointsMaterial({color:0xbadcec,size:.018,transparent:true,opacity:.4}));scene.add(particles);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,visible=true;const motion=document.querySelector('#motion');function label(){motion.textContent=paused?'Play motion ▷':'Pause motion Ⅱ';motion.setAttribute('aria-pressed',String(paused));}label();motion.onclick=()=>{paused=!paused;label();};reduced.addEventListener('change',e=>{paused=e.matches;dirty=true;label();});new IntersectionObserver(([e])=>visible=e.isIntersecting).observe(canvas);
let pointer=0;wrap.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'&&!paused)pointer=((e.clientX-wrap.getBoundingClientRect().left)/wrap.clientWidth-.5)*.13;});wrap.addEventListener('pointerleave',()=>pointer=0);
const journey=document.querySelector('.hero-journey'),hero=document.querySelector('.immersive-hero'),photo=document.querySelector('.family');let width=0,height=0,progress=0,dirty=true;
new ResizeObserver(()=>{width=wrap.clientWidth;height=wrap.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();dirty=true;}).observe(wrap);
addEventListener('scroll',()=>dirty=true,{passive:true});
let last=0,time=0;
function render(now){requestAnimationFrame(render);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;
if(dirty){const rect=journey.getBoundingClientRect();const state=scrollState(rect.top,rect.height,height);progress=reduced.matches?0:state.progress;hero.style.setProperty('--travel',progress);hero.style.setProperty('--intro-alpha',reduced.matches?1:state.intro);hero.style.setProperty('--intro-visibility',!reduced.matches&&state.intro===0?'hidden':'visible');hero.style.setProperty('--story-alpha',reduced.matches?0:state.story);if(photo&&!reduced.matches)photo.style.setProperty('--photo-shift',Math.max(-25,Math.min(25,(photo.getBoundingClientRect().top-innerHeight*.5)*.05))+'px');dirty=false;}
if(!visible)return;if(!paused)time+=dt;const mobile=width<=720;const p=progress;
if(mobile){camera.position.set(5-p*2,4.5+p*2,13-p*1.5);camera.lookAt(0,2.2,0);unit.position.set(.1+p*.2,-.5-p*.2,0);unit.scale.setScalar(.63);flagGroup.position.set(-1.5,-.9,-3);flagGroup.scale.setScalar(.6);camera.setViewOffset(width,height,0,-height*.17,width,height);}else{camera.clearViewOffset();camera.position.set(7-p*4,4.4+p*3,11-p*2);camera.lookAt(.3,2.1,0);unit.position.set(3.1-p*.4,.1,0);unit.scale.setScalar(1.15);flagGroup.position.set(2.5+p*1.6,-.15,-3.5-p*2);flagGroup.scale.setScalar(.85);}
unit.rotation.y=-.2-p*.8+pointer;unit.position.y+=Math.sin(time*.7)*.04;air.rotation.y=p*.2;air.position.y=Math.sin(time*.3)*.12;particles.rotation.y=time*.009;const pos=flagGeo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setZ(i,Math.sin(x*2-time*1.7+y*.7)*.28*(x/3.8)+Math.sin(x*4-time*2.1)*.07*(x/3.8));}pos.needsUpdate=true;flagGeo.computeVertexNormals();if(!paused)fan.rotation.y+=dt*3;renderer.render(scene,camera);}
requestAnimationFrame(render);
